"""empty message

Revision ID: 2763f0a4d99e
Revises: d000deda87f1
Create Date: 2016-12-25 21:43:21.503783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2763f0a4d99e'
down_revision = 'd000deda87f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
